website/internal/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('recruit/', views.recruit, name='recruit'),
    path('portfolio/', views.portfolio, name='portfolio'),
]

website/website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('internal.urls'))
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

website/internal/models.py
from django.db import models

# Create your models here.

website/internal/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'main.html')


def recruit(request):
    return render(request, 'internal/recruit.html')


def portfolio(request):
    return render(request, 'internal/port_list.html')

website/internal/templates/internal/about.html
{% load staticfiles %}

<section id="about" class="home-section" style="background-color: #ffffff">
  <div class="container">
    <div class="row" style="padding-bottom: 1.3%">
      <div class="offset-lg-2 col-lg-8">
        <div class="section-heading">
          <h5>ABOUT US</h5>
          <div class="heading-line"></div>
          <p style="font-family: 'Noto Sans KR'">웹 개발에 관심 있는 모두를 위한 연합동아리</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 about-img">
        <img src="{% static 'img/piro_about.jpg' %}" alt="">
      </div>

      <div class="col-lg-6 content">
        <h3>방학은 짧고 인생은 깁니다.</h3>
        <p>
          피로그래밍은 프로그래밍 공부를 하고 싶으나 어디서부터 시작해야 할지 막막한 비전공자들이 Python과 Django 프레임워크를 기반으로 웹 개발을 배우고
          자신만의 웹서비스를 만드는 동아리입니다.</p>
        <p>비전공자 기준으로 기초부터 차근차근 쉽게 공부하며 방학 동안 집중적으로 코딩에 전념하여 프로그래밍(웹 개발)의
          기반을 확보하는데 그 목표가 있습니다.
        </p>
        <p>
          여러분들을 위한 동아리입니다:<br>
          ✔ 프로그래밍을 배우고 싶지만, 첫 발을 내딛기 어려운 사람<br>
          ✔ 비전공자라서 프로그래밍 동아리에 지원조차 못했던 사람<br>
          ✔ 웹 개발에 관심 있는 디자인 전공자<br>
          ✔ 컴퓨터 관련 학과 전공자이지만 웹 개발 공부를 하고 싶은 사람<br>
          ✔ 웹 서비스로 구현하고 싶은 아이디어가 있는 사람<br>
        </p>
      </div>
    </div>
  </div>
  <div class="container wow zoomIn">
    <div class="row counters">
      <div class="col-lg-3 col-6 text-center">
        <p>동아리 역사</p>
        <span class="counter">6</span><h1>년</h1>
      </div>
      <div class="col-lg-3 col-6 text-center">
        <p>참여 학생 총</p>
        <span class="counter">360</span><h1>명</h1>
      </div>
      <div class="col-lg-3 col-6 text-center">
        <p>전국 참여 대학</p>
        <span class="counter">18</span><h1>곳</h1>
      </div>
      <div class="col-lg-3 col-6 text-center">
        <p>프로젝트 총</p>
        <span class="counter">72</span><h1>개</h1>
      </div>
    </div>
  </div>
</section>

website/internal/templates/internal/activity.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/activity.css' %}">

<section class="activity" id="activity">
    <div class="activity-info wow fadeInDown">
        <div class="row">
            <div class="col info-content">
            <h5>피로그래밍 활동</h5>
            <div class="heading-line"></div>
            <p style="font-family: 'Noto Sans KR'">방학 중에는 인터넷 강의, 선배 기수의 강의를 통해 웹 개발을 공부하고, 직접 만들고 싶은 웬서비스를 기획해 팀 단위로 나뉘어 협업한 프로젝트를 발표합니다.
            <br>방학 6주차부터 학기 중에는 선배 기수에서 선정한 프로그래밍 실력 향상에 도움이 되는 여러 주제를 직접 공부하고 발표하는 세션을 진행합니다.</p>
            </div>
        </div>
    </div>
    <div class="activity-content">
        <div class="row justify-content-center">
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_1.jpg' %}" alt="piro_activity_1" />
              <figcaption>
                <p>웹으로 문서를 공유하기 위한 약속인 마크업 언어 (HTML / CSS)를 배웁니다.<br><br>
                웹에서 동작하는 JavaScript와 Bootstrap을 이용하여 동적인 웹페이지를 만드는 것에 대해 배웁니다.</p>
                <div class="heading">
                  <h2>Week <span> 01</span></h2>
                </div>
              </figcaption>
            </figure>
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_2.jpg' %}" alt="piro_activity_2" />
              <figcaption>
                <p>Python을 통해 프로그래밍 언어 문법을 익히고 객체 지향 언어의 특징을 익힙니다.<br><br>
                소스 코드의 버전 관리 도구인 Git과 Github이라는 플랫폼의 사용 방법에 대해 배웁니다.</p>
                <div class="heading">
                  <h2>Week <span> 02</span></h2>
                </div>
              </figcaption>
            </figure>
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_3.jpg' %}" alt="piro_activity_3" />
              <figcaption>
                <p>Django를 통해 웹브라우저와 서버의 상호작용에 대해 배웁니다.<br><br>
                    Django 프레임워크의 구조를 이해하고 URL설계, MTV 패턴의 유기적인 연결, ORM, Django 폼 등 장고의 주요 기능에 대해 배웁니다.</p>
                <div class="heading">
                  <h2>Week <span> 03-05</span></h2>
                </div>
              </figcaption>
            </figure>
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_4.jpg' %}" alt="piro_activity_4" />
              <figcaption>
                <p>프로젝트를 개발, 완성, 배포하고 세션(프로젝트 발표)을 진행합니다.</p>
                <div class="heading">
                  <h2>Week <span> 06-08</span></h2>
                </div>
              </figcaption>
            </figure>
        </div>
    </div>
</section>

<div class="wow fadeInLeft">
    <div class="row" id="schedule">
        <div class="col info-content">
        <h5>피로그래밍 상반기 활동 일정</h5>
        <div class="heading-line"></div>
        <img src="{% static 'img/piro_timeline.png' %}" alt="piro_timeline" />
        </div>
    </div>
</div>

website/internal/templates/internal/intro.html
{% load staticfiles %}
<section id="home">
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    </ol>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/piro_intro_1.jpg' %}" class="d-block w-100" alt="리크루팅 공지">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/piro_intro_2.png' %}" class="d-block w-100" alt="리크루팅 공지 #2">
        </div>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
</section>
<div id="progress-container">
    <div class="progress-bar" id="myBar"></div>
</div>

website/internal/templates/internal/photo.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/slick-theme.css' %}">
<link rel="stylesheet" href="{% static 'css/slick.css' %}">

<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" src="{% static 'js/slick.min.js' %}"></script>
<script>
    $(document).ready(function(){
        $('.autoplay').slick({
          slidesToShow: 3,
          slidesToScroll: 1,
          autoplay: true,
          autoplaySpeed: 3000,
          infinite: true,
          dots: true,
          arrows: false,
          pauseOnHover:false,
        });
    });

    $('.slick-dots').on('click', function() {
    $('.autoplay').slick('slickPause');
    });
</script>
<section id="photo">
  <div style="margin-bottom: 4%;">
    <h5>피로그래밍 활동 사진</h5>
    <div class="heading-line"></div>
  </div>
  <div class="autoplay" style="margin:0px 2%">
    <div><img src="{% static 'img/piro_img_1.png' %}" alt="piro_img_1" /></div>
    <div><img src="{% static 'img/piro_img_2.png' %}" alt="piro_img_2" /></div>
    <div><img src="{% static 'img/piro_img_3.png' %}" alt="piro_img_3" /></div>
    <div><img src="{% static 'img/piro_img_4.png' %}" alt="piro_img_4" /></div>
    <div><img src="{% static 'img/piro_img_5.png' %}" alt="piro_img_5" /></div>
    <div><img src="{% static 'img/piro_img_6.png' %}" alt="piro_img_6" /></div>
    <div><img src="{% static 'img/piro_img_7.png' %}" alt="piro_img_7" /></div>
    <div><img src="{% static 'img/piro_img_8.png' %}" alt="piro_img_8" /></div>
    <div><img src="{% static 'img/piro_img_9.png' %}" alt="piro_img_9" /></div>
    <div><img src="{% static 'img/piro_img_10.png' %}" alt="piro_img_10" /></div>
    <div><img src="{% static 'img/piro_img_11.png' %}" alt="piro_img_11" /></div>
  </div>
</section>

website/internal/templates/internal/port.html
{% load staticfiles %}

<!--Photo for portfolio: https://ko.wix.com/logo/maker-->
<section id="port" class="home-section" style="background-color: #2C3E52">
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="section-heading">
        <h5 style="color:white">프로젝트</h5>
        <div class="heading-line"></div>
        <p style="font-family: 'Noto Sans KR'; color: white">피로그래밍 동아리원들은 6년간 총 72개의 프로젝트를 진행하였습니다.</p>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-12">

      <ul id="og-grid" class="og-grid">
        <li>
          <a>
            <img src="{% static 'img/piro_proj_1.png' %}" alt="piro_proj_1" />
          </a>
        </li>
        <li>
          <a>
            <img src="{% static 'img/piro_proj_2.png' %}" alt="piro_proj_2" />
          </a>
        </li>
        <li>
          <a>
            <img src="{% static 'img/piro_proj_3.png' %}" alt="piro_proj_3" />
          </a>
        </li>
        <li>
          <a>
            <img src="{% static 'img/piro_proj_4.png' %}" alt="piro_proj_4" />
          </a>
        </li>
        <li>
          <a>
            <img src="{% static 'img/piro_proj_5.png' %}" alt="piro_proj_5" />
          </a>
        </li>
        <li>
          <a>
            <img src="{% static 'img/piro_proj_6.png' %}" alt="piro_proj_6" />
          </a>
        </li>
        <li>
          <a>
            <img src="{% static 'img/piro_proj_7.png' %}" alt="piro_proj_7" />
          </a>
        </li>
        <li>
          <a>
            <img src="{% static 'img/piro_proj_8.png' %}" alt="piro_proj_8" />
          </a>
        </li>
      </ul>
    </div>
  </div>
</div>

<div class="text-center">
  <a class="btn btn-success" href="{% url "home:portfolio" %}" role="button" style="background-color: #25CCA0"><i class="fas fa-plus-circle" style="margin-right: 8px;"></i>자세히 보기</a>
</div>
</section>

website/internal/templates/internal/recruit.html
{% extends 'base.html' %}

{% block title %}
피로그래밍 - 모집
{% endblock %}

{% block content %}
<style>

</style>

<script>
function change_recruit() {
    document.getElementById("option4").style.color = 'white';
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="{% url "home:portfolio" %}";
}
change_recruit();

</script>
<div class="notice-list wow fadeInUp">
    <div class="jumbotron jumbotron-fluid">
        <div class="container">
            <h1 class="display-3">공지사항</h1>
            <p class="lead">피로그래밍 상세 모집일정과 관련 내용을 확인 하실 수 있습니다.</p>
        </div>
    </div>
    <!-- Needs Backend -->
    <div class="notice-table">
        <table class="table">
            <thead class="thead">
                <tr>
                    <th scope="col">번호</th>
                    <th scope="col">제목</th>
                    <th scope="col">모집일정</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>피로그래밍 12기</td>
                    <td>'19.11.00~00.00</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td>피로그래밍 11기</td>
                    <td>'19.05.00~00.00</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td>피로그래밍 10기</td>
                    <td>'18.11.00~00.00</td>
                </tr>
            </tbody>
        </table>
    </div>
</div>
{% endblock %}

website/internal/templates/main.html
{% extends 'base.html' %}

{% block title %}
피로그래밍
{% endblock %}

{% block content %}
    {% include 'internal/intro.html' %}
    {% include 'internal/about.html' %}
    {% include 'internal/activity.html' %}
    {% include 'internal/port.html' %}
    {% include 'internal/photo.html' %}
{% endblock %}

website/templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <!-- FONTAWESOME -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- OTHER FONTS USED -->



    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <!-- JS -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/menuspy.min.js' %}"></script>
    <script>
        $(document).ready(function(){
        $('.counter').counterUp();
        });
    </script>
    <script>
    $(function(){
        $('#back-to-top').on('click',function(e){
            e.preventDefault();
            $('html,body').animate({scrollTop:0},80);
    });

    $(window).scroll(function() {
        if ($(document).scrollTop() > 100) {
            $('#back-to-top').addClass('show');
        } else {
            $('#back-to-top').removeClass('show');
        }
        });
    });
    </script>
    <script>
        new WOW().init();
    </script>



    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
    <a id="back-to-top" href="#home"></a>
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    {% block script %}
    {% endblock %}
</body>
<script>
    var elm = document.querySelector('#navbar');
    var ms = new MenuSpy(elm);
</script>
</html>

website/templates/footer.html
<div id="foot">
    <div class="footer-buffer"></div>
    <div class="contact">
        <a href="https://www.facebook.com/p.rogramming3k/" target="_blank">
            <i class="fab fa-facebook fa-2x"></i>
        </a>
        <a href="mailto:pirogramming@gmail.com">
            <i class="fas fa-envelope fa-2x"></i>
        </a>
    </div>
    <footer class="container-fluid d-flex flex-column justify-content-center">
        <div class="row d-flex justify-content-center">
            &copy피로그래밍 | 회장 : 정성모 | 연락처: 010-1234-5678
        </div>
        <div class="row mt-1 d-flex justify-content-center" style="margin-bottom: 1%">
            서울특별시 관악구 관악로 1, 서울대학교 벤처경영 교육 및 연구 동아리
        </div>
    </footer>
</div>

website/templates/navbar.html
{% load staticfiles %}
<nav class="navbar navbar-expand-md navbar-dark" id="navbar">
    <div class="navbar-header">
        <a class="navbar-logo" href="{% url "home:home" %}">
        <img src="{% static 'img/piro_logo.jpg' %}" alt="piro_logo">
    </a>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a class="nav-link" id="option1" href="#about">ABOUT US</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#activity" id="option2">ACTIVITY </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#port" id="option3">PORTFOLIO </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "home:recruit" %}" id="option4">RECRUITMENT </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#board" id="option5">BOARD </a>
          </li>
        </ul>
        <ul class="nav navbar-nav navbar-right" id="sign-up">
          <li class="nav-item"><a class="nav-link"><i class="fas fa-user"></i>SIGN UP</a></li>
          <li class="nav-item"><a class="nav-link"><i class="fas fa-sign-in-alt"></i>LOGIN</a></li>
        </ul>
    </div>
</nav>